# Generated by Django 2.2.1 on 2019-05-25 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(max_length=30, verbose_name='last name')),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('Address', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('member_type', models.IntegerField(choices=[(1, 'international membership'), (2, 'national membership'), (3, 'no memership')], max_length=1, verbose_name='choose member type')),
            ],
            options={
                'verbose_name': 'member',
                'verbose_name_plural': 'members',
                'db_table': 'member',
            },
        ),
    ]
